# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration.ui'
#
# Created: Sat Jul  9 19:04:50 2016
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Calibration(object):
    def setupUi(self, Calibration):
        Calibration.setObjectName(_fromUtf8("Calibration"))
        Calibration.setWindowModality(QtCore.Qt.NonModal)
        Calibration.resize(800, 555)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Calibration.sizePolicy().hasHeightForWidth())
        Calibration.setSizePolicy(sizePolicy)
        Calibration.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Calibration)
        self.horizontalLayout_2.setMargin(9)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_3 = QtGui.QWidget(Calibration)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.horizontalLayout_3.setFont(font)
        self.horizontalLayout_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayout_3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setContentsMargins(5, 3, 5, 3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.horizontalLayout_3)
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(0,139,255);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(19, 36, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.op_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.op_MF.setFont(font)
        self.op_MF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.op_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.op_MF.setFrameShadow(QtGui.QFrame.Plain)
        self.op_MF.setTextFormat(QtCore.Qt.AutoText)
        self.op_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.op_MF.setIndent(0)
        self.op_MF.setObjectName(_fromUtf8("op_MF"))
        self.verticalLayout.addWidget(self.op_MF)
        self.inv_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.inv_MF.setFont(font)
        self.inv_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.inv_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inv_MF.setObjectName(_fromUtf8("inv_MF"))
        self.verticalLayout.addWidget(self.inv_MF)
        self.prim_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.prim_MF.setFont(font)
        self.prim_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.prim_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prim_MF.setObjectName(_fromUtf8("prim_MF"))
        self.verticalLayout.addWidget(self.prim_MF)
        self.trans_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.trans_MF.setFont(font)
        self.trans_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.trans_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trans_MF.setObjectName(_fromUtf8("trans_MF"))
        self.verticalLayout.addWidget(self.trans_MF)
        self.cap_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.cap_MF.setFont(font)
        self.cap_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.cap_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cap_MF.setObjectName(_fromUtf8("cap_MF"))
        self.verticalLayout.addWidget(self.cap_MF)
        self.pll_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pll_MF.setFont(font)
        self.pll_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pll_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pll_MF.setObjectName(_fromUtf8("pll_MF"))
        self.verticalLayout.addWidget(self.pll_MF)
        self.freq_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.freq_MF.setFont(font)
        self.freq_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.freq_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.freq_MF.setObjectName(_fromUtf8("freq_MF"))
        self.verticalLayout.addWidget(self.freq_MF)
        self.local_pot_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.local_pot_MF.setFont(font)
        self.local_pot_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.local_pot_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.local_pot_MF.setObjectName(_fromUtf8("local_pot_MF"))
        self.verticalLayout.addWidget(self.local_pot_MF)
        self.remote_pot_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.remote_pot_MF.setFont(font)
        self.remote_pot_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.remote_pot_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remote_pot_MF.setObjectName(_fromUtf8("remote_pot_MF"))
        self.verticalLayout.addWidget(self.remote_pot_MF)
        self.plc_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.plc_MF.setFont(font)
        self.plc_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.plc_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plc_MF.setObjectName(_fromUtf8("plc_MF"))
        self.verticalLayout.addWidget(self.plc_MF)
        self.mA1_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA1_MF.setFont(font)
        self.mA1_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.mA1_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mA1_MF.setObjectName(_fromUtf8("mA1_MF"))
        self.verticalLayout.addWidget(self.mA1_MF)
        self.mA2_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA2_MF.setFont(font)
        self.mA2_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.mA2_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mA2_MF.setObjectName(_fromUtf8("mA2_MF"))
        self.verticalLayout.addWidget(self.mA2_MF)
        self.mA3_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA3_MF.setFont(font)
        self.mA3_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.mA3_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mA3_MF.setObjectName(_fromUtf8("mA3_MF"))
        self.verticalLayout.addWidget(self.mA3_MF)
        self.mA4_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA4_MF.setFont(font)
        self.mA4_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.mA4_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mA4_MF.setObjectName(_fromUtf8("mA4_MF"))
        self.verticalLayout.addWidget(self.mA4_MF)
        self.pwr_MF = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pwr_MF.setFont(font)
        self.pwr_MF.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pwr_MF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwr_MF.setObjectName(_fromUtf8("pwr_MF"))
        self.verticalLayout.addWidget(self.pwr_MF)
        self.horizontalLayout.addWidget(self.frame)
        self.frame1 = QtGui.QFrame(self.horizontalLayout_3)
        self.frame1.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame1)
        self.verticalLayout_8.setMargin(3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label = QtGui.QLabel(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(101)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem1)
        self.op_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.op_mf_IN.sizePolicy().hasHeightForWidth())
        self.op_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.op_mf_IN.setFont(font)
        self.op_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.op_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.op_mf_IN.setMinimum(1.0)
        self.op_mf_IN.setMaximum(100.0)
        self.op_mf_IN.setProperty("value", 1.0)
        self.op_mf_IN.setObjectName(_fromUtf8("op_mf_IN"))
        self.verticalLayout_8.addWidget(self.op_mf_IN)
        self.inv_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inv_mf_IN.sizePolicy().hasHeightForWidth())
        self.inv_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inv_mf_IN.setFont(font)
        self.inv_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.inv_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.inv_mf_IN.setMinimum(1.0)
        self.inv_mf_IN.setMaximum(100.0)
        self.inv_mf_IN.setProperty("value", 1.0)
        self.inv_mf_IN.setObjectName(_fromUtf8("inv_mf_IN"))
        self.verticalLayout_8.addWidget(self.inv_mf_IN)
        self.prim_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prim_mf_IN.sizePolicy().hasHeightForWidth())
        self.prim_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.prim_mf_IN.setFont(font)
        self.prim_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.prim_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.prim_mf_IN.setMinimum(1.0)
        self.prim_mf_IN.setMaximum(100.0)
        self.prim_mf_IN.setProperty("value", 1.0)
        self.prim_mf_IN.setObjectName(_fromUtf8("prim_mf_IN"))
        self.verticalLayout_8.addWidget(self.prim_mf_IN)
        self.trans_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans_mf_IN.sizePolicy().hasHeightForWidth())
        self.trans_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.trans_mf_IN.setFont(font)
        self.trans_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.trans_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.trans_mf_IN.setMinimum(1.0)
        self.trans_mf_IN.setMaximum(100.0)
        self.trans_mf_IN.setProperty("value", 1.0)
        self.trans_mf_IN.setObjectName(_fromUtf8("trans_mf_IN"))
        self.verticalLayout_8.addWidget(self.trans_mf_IN)
        self.cap_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cap_mf_IN.sizePolicy().hasHeightForWidth())
        self.cap_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cap_mf_IN.setFont(font)
        self.cap_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cap_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.cap_mf_IN.setMinimum(1.0)
        self.cap_mf_IN.setMaximum(100.0)
        self.cap_mf_IN.setProperty("value", 1.0)
        self.cap_mf_IN.setObjectName(_fromUtf8("cap_mf_IN"))
        self.verticalLayout_8.addWidget(self.cap_mf_IN)
        self.pll_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pll_mf_IN.sizePolicy().hasHeightForWidth())
        self.pll_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pll_mf_IN.setFont(font)
        self.pll_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pll_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.pll_mf_IN.setMinimum(1.0)
        self.pll_mf_IN.setMaximum(100.0)
        self.pll_mf_IN.setProperty("value", 1.0)
        self.pll_mf_IN.setObjectName(_fromUtf8("pll_mf_IN"))
        self.verticalLayout_8.addWidget(self.pll_mf_IN)
        self.freq_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_mf_IN.sizePolicy().hasHeightForWidth())
        self.freq_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.freq_mf_IN.setFont(font)
        self.freq_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.freq_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.freq_mf_IN.setMinimum(1.0)
        self.freq_mf_IN.setMaximum(100.0)
        self.freq_mf_IN.setProperty("value", 1.0)
        self.freq_mf_IN.setObjectName(_fromUtf8("freq_mf_IN"))
        self.verticalLayout_8.addWidget(self.freq_mf_IN)
        self.local_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.local_mf_IN.sizePolicy().hasHeightForWidth())
        self.local_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.local_mf_IN.setFont(font)
        self.local_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.local_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.local_mf_IN.setMinimum(1.0)
        self.local_mf_IN.setMaximum(100.0)
        self.local_mf_IN.setProperty("value", 1.0)
        self.local_mf_IN.setObjectName(_fromUtf8("local_mf_IN"))
        self.verticalLayout_8.addWidget(self.local_mf_IN)
        self.remote_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remote_mf_IN.sizePolicy().hasHeightForWidth())
        self.remote_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.remote_mf_IN.setFont(font)
        self.remote_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.remote_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.remote_mf_IN.setMinimum(1.0)
        self.remote_mf_IN.setMaximum(100.0)
        self.remote_mf_IN.setProperty("value", 1.0)
        self.remote_mf_IN.setObjectName(_fromUtf8("remote_mf_IN"))
        self.verticalLayout_8.addWidget(self.remote_mf_IN)
        self.plc_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plc_mf_IN.sizePolicy().hasHeightForWidth())
        self.plc_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plc_mf_IN.setFont(font)
        self.plc_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.plc_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.plc_mf_IN.setMinimum(1.0)
        self.plc_mf_IN.setMaximum(100.0)
        self.plc_mf_IN.setProperty("value", 1.0)
        self.plc_mf_IN.setObjectName(_fromUtf8("plc_mf_IN"))
        self.verticalLayout_8.addWidget(self.plc_mf_IN)
        self.mA1_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mA1_mf_IN.sizePolicy().hasHeightForWidth())
        self.mA1_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mA1_mf_IN.setFont(font)
        self.mA1_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA1_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.mA1_mf_IN.setMinimum(1.0)
        self.mA1_mf_IN.setMaximum(100.0)
        self.mA1_mf_IN.setProperty("value", 1.0)
        self.mA1_mf_IN.setObjectName(_fromUtf8("mA1_mf_IN"))
        self.verticalLayout_8.addWidget(self.mA1_mf_IN)
        self.mA2_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mA2_mf_IN.sizePolicy().hasHeightForWidth())
        self.mA2_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mA2_mf_IN.setFont(font)
        self.mA2_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA2_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.mA2_mf_IN.setMinimum(1.0)
        self.mA2_mf_IN.setMaximum(100.0)
        self.mA2_mf_IN.setProperty("value", 1.0)
        self.mA2_mf_IN.setObjectName(_fromUtf8("mA2_mf_IN"))
        self.verticalLayout_8.addWidget(self.mA2_mf_IN)
        self.mA3_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mA3_mf_IN.sizePolicy().hasHeightForWidth())
        self.mA3_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mA3_mf_IN.setFont(font)
        self.mA3_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA3_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.mA3_mf_IN.setMinimum(1.0)
        self.mA3_mf_IN.setMaximum(100.0)
        self.mA3_mf_IN.setProperty("value", 1.0)
        self.mA3_mf_IN.setObjectName(_fromUtf8("mA3_mf_IN"))
        self.verticalLayout_8.addWidget(self.mA3_mf_IN)
        self.mA4_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mA4_mf_IN.sizePolicy().hasHeightForWidth())
        self.mA4_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mA4_mf_IN.setFont(font)
        self.mA4_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA4_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.mA4_mf_IN.setMinimum(1.0)
        self.mA4_mf_IN.setMaximum(100.0)
        self.mA4_mf_IN.setProperty("value", 1.0)
        self.mA4_mf_IN.setObjectName(_fromUtf8("mA4_mf_IN"))
        self.verticalLayout_8.addWidget(self.mA4_mf_IN)
        self.pwr_mf_IN = QtGui.QDoubleSpinBox(self.frame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwr_mf_IN.sizePolicy().hasHeightForWidth())
        self.pwr_mf_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pwr_mf_IN.setFont(font)
        self.pwr_mf_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pwr_mf_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.pwr_mf_IN.setMinimum(1.0)
        self.pwr_mf_IN.setMaximum(100.0)
        self.pwr_mf_IN.setProperty("value", 1.0)
        self.pwr_mf_IN.setObjectName(_fromUtf8("pwr_mf_IN"))
        self.verticalLayout_8.addWidget(self.pwr_mf_IN)
        self.horizontalLayout.addWidget(self.frame1)
        self.frame2 = QtGui.QFrame(self.horizontalLayout_3)
        self.frame2.setStyleSheet(_fromUtf8("background-color: rgb(0, 139,255);"))
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame2)
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_7.setMargin(3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem2 = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.label_21 = QtGui.QLabel(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setToolTip(_fromUtf8(""))
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setScaledContents(True)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_20 = QtGui.QLabel(self.frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 0))
        self.label_20.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_19 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.label_18 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_23 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_7.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_7.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_7.addWidget(self.label_25)
        self.label_27 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_7.addWidget(self.label_27)
        self.label_26 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_7.addWidget(self.label_26)
        self.label_28 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_7.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_7.addWidget(self.label_29)
        self.label_31 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_7.addWidget(self.label_31)
        self.label_30 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_7.addWidget(self.label_30)
        self.label_32 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_7.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_7.addWidget(self.label_33)
        self.horizontalLayout.addWidget(self.frame2)
        self.frame3 = QtGui.QFrame(self.horizontalLayout_3)
        self.frame3.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.frame3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame3.setObjectName(_fromUtf8("frame3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame3)
        self.verticalLayout_6.setMargin(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_34 = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_6.addWidget(self.label_34)
        self.op_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.op_mf_Actual.setFont(font)
        self.op_mf_Actual.setAutoFillBackground(False)
        self.op_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.op_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.op_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.op_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.op_mf_Actual.setWordWrap(False)
        self.op_mf_Actual.setObjectName(_fromUtf8("op_mf_Actual"))
        self.verticalLayout_6.addWidget(self.op_mf_Actual)
        self.inv_mf_Actual_2 = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.inv_mf_Actual_2.setFont(font)
        self.inv_mf_Actual_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.inv_mf_Actual_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.inv_mf_Actual_2.setFrameShadow(QtGui.QFrame.Plain)
        self.inv_mf_Actual_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inv_mf_Actual_2.setObjectName(_fromUtf8("inv_mf_Actual_2"))
        self.verticalLayout_6.addWidget(self.inv_mf_Actual_2)
        self.prim_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.prim_mf_Actual.setFont(font)
        self.prim_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.prim_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.prim_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.prim_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.prim_mf_Actual.setObjectName(_fromUtf8("prim_mf_Actual"))
        self.verticalLayout_6.addWidget(self.prim_mf_Actual)
        self.trans_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.trans_mf_Actual.setFont(font)
        self.trans_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.trans_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.trans_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.trans_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.trans_mf_Actual.setObjectName(_fromUtf8("trans_mf_Actual"))
        self.verticalLayout_6.addWidget(self.trans_mf_Actual)
        self.cap_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.cap_mf_Actual.setFont(font)
        self.cap_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cap_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.cap_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.cap_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.cap_mf_Actual.setObjectName(_fromUtf8("cap_mf_Actual"))
        self.verticalLayout_6.addWidget(self.cap_mf_Actual)
        self.pll_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pll_mf_Actual.setFont(font)
        self.pll_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pll_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.pll_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.pll_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.pll_mf_Actual.setObjectName(_fromUtf8("pll_mf_Actual"))
        self.verticalLayout_6.addWidget(self.pll_mf_Actual)
        self.freq_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.freq_mf_Actual.setFont(font)
        self.freq_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.freq_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.freq_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.freq_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.freq_mf_Actual.setObjectName(_fromUtf8("freq_mf_Actual"))
        self.verticalLayout_6.addWidget(self.freq_mf_Actual)
        self.local_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.local_mf_Actual.setFont(font)
        self.local_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.local_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.local_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.local_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.local_mf_Actual.setObjectName(_fromUtf8("local_mf_Actual"))
        self.verticalLayout_6.addWidget(self.local_mf_Actual)
        self.remote_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.remote_mf_Actual.setFont(font)
        self.remote_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.remote_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.remote_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.remote_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.remote_mf_Actual.setObjectName(_fromUtf8("remote_mf_Actual"))
        self.verticalLayout_6.addWidget(self.remote_mf_Actual)
        self.plc_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.plc_mf_Actual.setFont(font)
        self.plc_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.plc_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.plc_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.plc_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.plc_mf_Actual.setObjectName(_fromUtf8("plc_mf_Actual"))
        self.verticalLayout_6.addWidget(self.plc_mf_Actual)
        self.mA1_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA1_mf_Actual.setFont(font)
        self.mA1_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA1_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA1_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.mA1_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.mA1_mf_Actual.setObjectName(_fromUtf8("mA1_mf_Actual"))
        self.verticalLayout_6.addWidget(self.mA1_mf_Actual)
        self.mA2_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA2_mf_Actual.setFont(font)
        self.mA2_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA2_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA2_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.mA2_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.mA2_mf_Actual.setObjectName(_fromUtf8("mA2_mf_Actual"))
        self.verticalLayout_6.addWidget(self.mA2_mf_Actual)
        self.mA3_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA3_mf_Actual.setFont(font)
        self.mA3_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA3_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA3_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.mA3_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.mA3_mf_Actual.setObjectName(_fromUtf8("mA3_mf_Actual"))
        self.verticalLayout_6.addWidget(self.mA3_mf_Actual)
        self.mA4_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA4_mf_Actual.setFont(font)
        self.mA4_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA4_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA4_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.mA4_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.mA4_mf_Actual.setObjectName(_fromUtf8("mA4_mf_Actual"))
        self.verticalLayout_6.addWidget(self.mA4_mf_Actual)
        self.pwr_mf_Actual = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pwr_mf_Actual.setFont(font)
        self.pwr_mf_Actual.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pwr_mf_Actual.setFrameShape(QtGui.QFrame.NoFrame)
        self.pwr_mf_Actual.setFrameShadow(QtGui.QFrame.Plain)
        self.pwr_mf_Actual.setAlignment(QtCore.Qt.AlignCenter)
        self.pwr_mf_Actual.setObjectName(_fromUtf8("pwr_mf_Actual"))
        self.verticalLayout_6.addWidget(self.pwr_mf_Actual)
        self.horizontalLayout.addWidget(self.frame3)
        self.frame4 = QtGui.QFrame(self.horizontalLayout_3)
        self.frame4.setStyleSheet(_fromUtf8("background-color: rgb(0,139, 255);"))
        self.frame4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame4.setObjectName(_fromUtf8("frame4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame4)
        self.verticalLayout_5.setMargin(3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(20, 36, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.label_42 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_5.addWidget(self.label_42)
        self.label_48 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.verticalLayout_5.addWidget(self.label_48)
        self.label_47 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.verticalLayout_5.addWidget(self.label_47)
        self.label_50 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.verticalLayout_5.addWidget(self.label_50)
        self.label_51 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.verticalLayout_5.addWidget(self.label_51)
        self.label_49 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.verticalLayout_5.addWidget(self.label_49)
        self.label_46 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.verticalLayout_5.addWidget(self.label_46)
        self.label_45 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.verticalLayout_5.addWidget(self.label_45)
        self.label_44 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_5.addWidget(self.label_44)
        self.label_41 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_5.addWidget(self.label_41)
        self.label_40 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_5.addWidget(self.label_40)
        self.label_39 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_5.addWidget(self.label_39)
        self.label_38 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_5.addWidget(self.label_38)
        self.label_37 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_5.addWidget(self.label_37)
        self.label_36 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_5.addWidget(self.label_36)
        self.label_35 = QtGui.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_5.addWidget(self.label_35)
        self.horizontalLayout.addWidget(self.frame4)
        self.frame5 = QtGui.QFrame(self.horizontalLayout_3)
        self.frame5.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);\n"
""))
        self.frame5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame5.setObjectName(_fromUtf8("frame5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame5)
        self.verticalLayout_4.setMargin(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_52 = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_52.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_52.setFrameShadow(QtGui.QFrame.Plain)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.verticalLayout_4.addWidget(self.label_52)
        self.op_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.op_mf_Calib.setFont(font)
        self.op_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.op_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.op_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.op_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.op_mf_Calib.setObjectName(_fromUtf8("op_mf_Calib"))
        self.verticalLayout_4.addWidget(self.op_mf_Calib)
        self.inv_mf_Calib_2 = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.inv_mf_Calib_2.setFont(font)
        self.inv_mf_Calib_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.inv_mf_Calib_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.inv_mf_Calib_2.setFrameShadow(QtGui.QFrame.Plain)
        self.inv_mf_Calib_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inv_mf_Calib_2.setObjectName(_fromUtf8("inv_mf_Calib_2"))
        self.verticalLayout_4.addWidget(self.inv_mf_Calib_2)
        self.prim_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.prim_mf_Calib.setFont(font)
        self.prim_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.prim_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.prim_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.prim_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.prim_mf_Calib.setObjectName(_fromUtf8("prim_mf_Calib"))
        self.verticalLayout_4.addWidget(self.prim_mf_Calib)
        self.trans_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.trans_mf_Calib.setFont(font)
        self.trans_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.trans_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.trans_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.trans_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.trans_mf_Calib.setObjectName(_fromUtf8("trans_mf_Calib"))
        self.verticalLayout_4.addWidget(self.trans_mf_Calib)
        self.cap_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.cap_mf_Calib.setFont(font)
        self.cap_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cap_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.cap_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.cap_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.cap_mf_Calib.setObjectName(_fromUtf8("cap_mf_Calib"))
        self.verticalLayout_4.addWidget(self.cap_mf_Calib)
        self.pll_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pll_mf_Calib.setFont(font)
        self.pll_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pll_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.pll_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.pll_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.pll_mf_Calib.setObjectName(_fromUtf8("pll_mf_Calib"))
        self.verticalLayout_4.addWidget(self.pll_mf_Calib)
        self.freq_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.freq_mf_Calib.setFont(font)
        self.freq_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.freq_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.freq_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.freq_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.freq_mf_Calib.setObjectName(_fromUtf8("freq_mf_Calib"))
        self.verticalLayout_4.addWidget(self.freq_mf_Calib)
        self.local_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.local_mf_Calib.setFont(font)
        self.local_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.local_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.local_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.local_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.local_mf_Calib.setObjectName(_fromUtf8("local_mf_Calib"))
        self.verticalLayout_4.addWidget(self.local_mf_Calib)
        self.remote_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.remote_mf_Calib.setFont(font)
        self.remote_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.remote_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.remote_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.remote_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.remote_mf_Calib.setObjectName(_fromUtf8("remote_mf_Calib"))
        self.verticalLayout_4.addWidget(self.remote_mf_Calib)
        self.plc_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.plc_mf_Calib.setFont(font)
        self.plc_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.plc_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.plc_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.plc_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.plc_mf_Calib.setObjectName(_fromUtf8("plc_mf_Calib"))
        self.verticalLayout_4.addWidget(self.plc_mf_Calib)
        self.mA1_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA1_mf_Calib.setFont(font)
        self.mA1_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA1_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA1_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.mA1_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.mA1_mf_Calib.setObjectName(_fromUtf8("mA1_mf_Calib"))
        self.verticalLayout_4.addWidget(self.mA1_mf_Calib)
        self.mA2_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA2_mf_Calib.setFont(font)
        self.mA2_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA2_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA2_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.mA2_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.mA2_mf_Calib.setObjectName(_fromUtf8("mA2_mf_Calib"))
        self.verticalLayout_4.addWidget(self.mA2_mf_Calib)
        self.mA3_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA3_mf_Calib.setFont(font)
        self.mA3_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA3_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA3_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.mA3_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.mA3_mf_Calib.setObjectName(_fromUtf8("mA3_mf_Calib"))
        self.verticalLayout_4.addWidget(self.mA3_mf_Calib)
        self.mA4_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.mA4_mf_Calib.setFont(font)
        self.mA4_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mA4_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.mA4_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.mA4_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.mA4_mf_Calib.setObjectName(_fromUtf8("mA4_mf_Calib"))
        self.verticalLayout_4.addWidget(self.mA4_mf_Calib)
        self.pwr_mf_Calib = QtGui.QLabel(self.frame5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pwr_mf_Calib.setFont(font)
        self.pwr_mf_Calib.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pwr_mf_Calib.setFrameShape(QtGui.QFrame.NoFrame)
        self.pwr_mf_Calib.setFrameShadow(QtGui.QFrame.Plain)
        self.pwr_mf_Calib.setAlignment(QtCore.Qt.AlignCenter)
        self.pwr_mf_Calib.setObjectName(_fromUtf8("pwr_mf_Calib"))
        self.verticalLayout_4.addWidget(self.pwr_mf_Calib)
        self.horizontalLayout.addWidget(self.frame5)
        self.verticalLayout_3 = QtGui.QFrame(self.horizontalLayout_3)
        self.verticalLayout_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalLayout_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalLayout_3.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayout_3)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(20, 491, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.btn_bck = QtGui.QPushButton(self.verticalLayout_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bck.setFont(font)
        self.btn_bck.setMouseTracking(True)
        self.btn_bck.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.btn_bck.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Picture12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_bck.setIcon(icon)
        self.btn_bck.setIconSize(QtCore.QSize(24, 18))
        self.btn_bck.setAutoDefault(True)
        self.btn_bck.setObjectName(_fromUtf8("btn_bck"))
        self.verticalLayout_2.addWidget(self.btn_bck)
        self.horizontalLayout.addWidget(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.horizontalLayout_3)

        self.retranslateUi(Calibration)
        QtCore.QMetaObject.connectSlotsByName(Calibration)

    def retranslateUi(self, Calibration):
        Calibration.setWindowTitle(QtGui.QApplication.translate("Calibration", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.op_MF.setText(QtGui.QApplication.translate("Calibration", "OP Volt MF", None, QtGui.QApplication.UnicodeUTF8))
        self.inv_MF.setText(QtGui.QApplication.translate("Calibration", "INV Current MF", None, QtGui.QApplication.UnicodeUTF8))
        self.prim_MF.setText(QtGui.QApplication.translate("Calibration", "Primary Volt MF", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_MF.setText(QtGui.QApplication.translate("Calibration", "Trans Volt MF", None, QtGui.QApplication.UnicodeUTF8))
        self.cap_MF.setText(QtGui.QApplication.translate("Calibration", "CAP Volt MF", None, QtGui.QApplication.UnicodeUTF8))
        self.pll_MF.setText(QtGui.QApplication.translate("Calibration", "PLL MF", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_MF.setText(QtGui.QApplication.translate("Calibration", "Freq MF", None, QtGui.QApplication.UnicodeUTF8))
        self.local_pot_MF.setText(QtGui.QApplication.translate("Calibration", "Local Pot MF", None, QtGui.QApplication.UnicodeUTF8))
        self.remote_pot_MF.setText(QtGui.QApplication.translate("Calibration", "Remote Pot MF", None, QtGui.QApplication.UnicodeUTF8))
        self.plc_MF.setText(QtGui.QApplication.translate("Calibration", "PLC mAmp MF", None, QtGui.QApplication.UnicodeUTF8))
        self.mA1_MF.setText(QtGui.QApplication.translate("Calibration", "mAmp1 MF", None, QtGui.QApplication.UnicodeUTF8))
        self.mA2_MF.setText(QtGui.QApplication.translate("Calibration", "mAmp2 MF", None, QtGui.QApplication.UnicodeUTF8))
        self.mA3_MF.setText(QtGui.QApplication.translate("Calibration", "mAmp3 MF", None, QtGui.QApplication.UnicodeUTF8))
        self.mA4_MF.setText(QtGui.QApplication.translate("Calibration", "mAmp4 MF", None, QtGui.QApplication.UnicodeUTF8))
        self.pwr_MF.setText(QtGui.QApplication.translate("Calibration", "Power MF", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Calibration", "Multiplying Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Calibration", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Calibration", "Actual Value", None, QtGui.QApplication.UnicodeUTF8))
        self.op_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.inv_mf_Actual_2.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.prim_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cap_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pll_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.local_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.remote_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.plc_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA1_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA2_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA3_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA4_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pwr_mf_Actual.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Calibration", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("Calibration", "Calibrated Value", None, QtGui.QApplication.UnicodeUTF8))
        self.op_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.inv_mf_Calib_2.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.prim_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cap_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pll_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.local_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.remote_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.plc_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA1_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA2_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA3_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.mA4_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pwr_mf_Calib.setText(QtGui.QApplication.translate("Calibration", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
