# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comm_params.ui'
#
# Created: Mon Jul 11 11:54:25 2016
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CommParams(object):
    def setupUi(self, CommParams):
        CommParams.setObjectName(_fromUtf8("CommParams"))
        CommParams.resize(800, 480)
        CommParams.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(CommParams)
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_4 = QtGui.QWidget(CommParams)
        self.horizontalLayout_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayout_4)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setContentsMargins(4, 3, 4, 3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_1 = QtGui.QFrame(self.horizontalLayout_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayout_1.sizePolicy().hasHeightForWidth())
        self.verticalLayout_1.setSizePolicy(sizePolicy)
        self.verticalLayout_1.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalLayout_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalLayout_1.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_1.setObjectName(_fromUtf8("verticalLayout_1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayout_1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.visa_rsrc_IN = QtGui.QComboBox(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visa_rsrc_IN.sizePolicy().hasHeightForWidth())
        self.visa_rsrc_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.visa_rsrc_IN.setFont(font)
        self.visa_rsrc_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.visa_rsrc_IN.setObjectName(_fromUtf8("visa_rsrc_IN"))
        self.visa_rsrc_IN.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.visa_rsrc_IN)
        self.label_2 = QtGui.QLabel(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.baud_IN = QtGui.QComboBox(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baud_IN.sizePolicy().hasHeightForWidth())
        self.baud_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baud_IN.setFont(font)
        self.baud_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.baud_IN.setObjectName(_fromUtf8("baud_IN"))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.baud_IN.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.baud_IN)
        self.label_3 = QtGui.QLabel(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.flowCtrl_IN = QtGui.QComboBox(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flowCtrl_IN.sizePolicy().hasHeightForWidth())
        self.flowCtrl_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flowCtrl_IN.setFont(font)
        self.flowCtrl_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.flowCtrl_IN.setObjectName(_fromUtf8("flowCtrl_IN"))
        self.flowCtrl_IN.addItem(_fromUtf8(""))
        self.flowCtrl_IN.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.flowCtrl_IN)
        self.label_5 = QtGui.QLabel(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.parity_IN = QtGui.QComboBox(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parity_IN.sizePolicy().hasHeightForWidth())
        self.parity_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.parity_IN.setFont(font)
        self.parity_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.parity_IN.setObjectName(_fromUtf8("parity_IN"))
        self.parity_IN.addItem(_fromUtf8(""))
        self.parity_IN.addItem(_fromUtf8(""))
        self.parity_IN.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.parity_IN)
        self.label_4 = QtGui.QLabel(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.timeout_IN = QtGui.QSpinBox(self.verticalLayout_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeout_IN.sizePolicy().hasHeightForWidth())
        self.timeout_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeout_IN.setFont(font)
        self.timeout_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.timeout_IN.setMaximum(5000)
        self.timeout_IN.setSingleStep(100)
        self.timeout_IN.setProperty("value", 1000)
        self.timeout_IN.setObjectName(_fromUtf8("timeout_IN"))
        self.verticalLayout_4.addWidget(self.timeout_IN)
        spacerItem = QtGui.QSpacerItem(20, 35, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.verticalLayout_1)
        self.verticalLayout_3 = QtGui.QFrame(self.horizontalLayout_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayout_3.sizePolicy().hasHeightForWidth())
        self.verticalLayout_3.setSizePolicy(sizePolicy)
        self.verticalLayout_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalLayout_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalLayout_3.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayout_3)
        self.verticalLayout_2.setContentsMargins(8, 6, 8, 6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_10 = QtGui.QLabel(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.mode_IN = QtGui.QComboBox(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_IN.sizePolicy().hasHeightForWidth())
        self.mode_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mode_IN.setFont(font)
        self.mode_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.mode_IN.setObjectName(_fromUtf8("mode_IN"))
        self.mode_IN.addItem(_fromUtf8(""))
        self.mode_IN.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.mode_IN)
        self.label_11 = QtGui.QLabel(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.slaveAddr_IN = QtGui.QSpinBox(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slaveAddr_IN.sizePolicy().hasHeightForWidth())
        self.slaveAddr_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.slaveAddr_IN.setFont(font)
        self.slaveAddr_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.slaveAddr_IN.setObjectName(_fromUtf8("slaveAddr_IN"))
        self.verticalLayout_2.addWidget(self.slaveAddr_IN)
        self.label_7 = QtGui.QLabel(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.access_IN = QtGui.QComboBox(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.access_IN.sizePolicy().hasHeightForWidth())
        self.access_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.access_IN.setFont(font)
        self.access_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.access_IN.setObjectName(_fromUtf8("access_IN"))
        self.access_IN.addItem(_fromUtf8(""))
        self.access_IN.addItem(_fromUtf8(""))
        self.access_IN.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.access_IN)
        self.label_8 = QtGui.QLabel(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.length_IN = QtGui.QSpinBox(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_IN.sizePolicy().hasHeightForWidth())
        self.length_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.length_IN.setFont(font)
        self.length_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.length_IN.setMaximum(999)
        self.length_IN.setObjectName(_fromUtf8("length_IN"))
        self.verticalLayout_2.addWidget(self.length_IN)
        self.label_9 = QtGui.QLabel(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.readQty_IN = QtGui.QSpinBox(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readQty_IN.sizePolicy().hasHeightForWidth())
        self.readQty_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.readQty_IN.setFont(font)
        self.readQty_IN.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.readQty_IN.setObjectName(_fromUtf8("readQty_IN"))
        self.verticalLayout_2.addWidget(self.readQty_IN)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(232, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_bck = QtGui.QPushButton(self.verticalLayout_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bck.sizePolicy().hasHeightForWidth())
        self.btn_bck.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bck.setFont(font)
        self.btn_bck.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.btn_bck.setIconSize(QtCore.QSize(37, 15))
        self.btn_bck.setObjectName(_fromUtf8("btn_bck"))
        self.horizontalLayout_3.addWidget(self.btn_bck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.horizontalLayout_4)

        self.retranslateUi(CommParams)
        self.visa_rsrc_IN.setCurrentIndex(0)
        self.baud_IN.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(CommParams)

    def retranslateUi(self, CommParams):
        CommParams.setWindowTitle(QtGui.QApplication.translate("CommParams", "Communication Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CommParams", "VISA Resource Name", None, QtGui.QApplication.UnicodeUTF8))
        self.visa_rsrc_IN.setItemText(0, QtGui.QApplication.translate("CommParams", "/dev/ttyAMA0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CommParams", "Baud Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(0, QtGui.QApplication.translate("CommParams", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(1, QtGui.QApplication.translate("CommParams", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(2, QtGui.QApplication.translate("CommParams", "38400", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(3, QtGui.QApplication.translate("CommParams", "57600", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(4, QtGui.QApplication.translate("CommParams", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(5, QtGui.QApplication.translate("CommParams", "230400", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(6, QtGui.QApplication.translate("CommParams", "460800", None, QtGui.QApplication.UnicodeUTF8))
        self.baud_IN.setItemText(7, QtGui.QApplication.translate("CommParams", "921600", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CommParams", "Flow Control", None, QtGui.QApplication.UnicodeUTF8))
        self.flowCtrl_IN.setItemText(0, QtGui.QApplication.translate("CommParams", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.flowCtrl_IN.setItemText(1, QtGui.QApplication.translate("CommParams", "Hardware Flow Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CommParams", "Parity", None, QtGui.QApplication.UnicodeUTF8))
        self.parity_IN.setItemText(0, QtGui.QApplication.translate("CommParams", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.parity_IN.setItemText(1, QtGui.QApplication.translate("CommParams", "Even", None, QtGui.QApplication.UnicodeUTF8))
        self.parity_IN.setItemText(2, QtGui.QApplication.translate("CommParams", "Odd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CommParams", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CommParams", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_IN.setItemText(0, QtGui.QApplication.translate("CommParams", "RTU", None, QtGui.QApplication.UnicodeUTF8))
        self.mode_IN.setItemText(1, QtGui.QApplication.translate("CommParams", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CommParams", "Slave Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CommParams", "Access", None, QtGui.QApplication.UnicodeUTF8))
        self.access_IN.setItemText(0, QtGui.QApplication.translate("CommParams", "Read/Write", None, QtGui.QApplication.UnicodeUTF8))
        self.access_IN.setItemText(1, QtGui.QApplication.translate("CommParams", "Read", None, QtGui.QApplication.UnicodeUTF8))
        self.access_IN.setItemText(2, QtGui.QApplication.translate("CommParams", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CommParams", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CommParams", "Read Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_bck.setText(QtGui.QApplication.translate("CommParams", "Save and Exit", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
