# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interlock_params.ui'
#
# Created: Sun Jul 10 09:55:52 2016
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InterlockParams(object):
    def setupUi(self, InterlockParams):
        InterlockParams.setObjectName(_fromUtf8("InterlockParams"))
        InterlockParams.resize(800, 420)
        InterlockParams.setMaximumSize(QtCore.QSize(800, 420))
        InterlockParams.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(InterlockParams)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_7 = QtGui.QWidget(InterlockParams)
        self.verticalLayout_7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayout_7)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(5, 3, 5, 3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QWidget(self.verticalLayout_7)
        self.horizontalLayout_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayout_5)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalFrame_4 = QtGui.QFrame(self.horizontalLayout_5)
        self.verticalFrame_4.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalFrame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame_4.setObjectName(_fromUtf8("verticalFrame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setMargin(3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.freqLimit_OUT = QtGui.QLabel(self.verticalFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.freqLimit_OUT.setFont(font)
        self.freqLimit_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.freqLimit_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.freqLimit_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.freqLimit_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.freqLimit_OUT.setObjectName(_fromUtf8("freqLimit_OUT"))
        self.verticalLayout_5.addWidget(self.freqLimit_OUT)
        self.freqTrip_OUT = QtGui.QLabel(self.verticalFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.freqTrip_OUT.setFont(font)
        self.freqTrip_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.freqTrip_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.freqTrip_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.freqTrip_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.freqTrip_OUT.setObjectName(_fromUtf8("freqTrip_OUT"))
        self.verticalLayout_5.addWidget(self.freqTrip_OUT)
        self.voltLimit_OUT = QtGui.QLabel(self.verticalFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voltLimit_OUT.setFont(font)
        self.voltLimit_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.voltLimit_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.voltLimit_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.voltLimit_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.voltLimit_OUT.setObjectName(_fromUtf8("voltLimit_OUT"))
        self.verticalLayout_5.addWidget(self.voltLimit_OUT)
        self.voltTrip_OUT = QtGui.QLabel(self.verticalFrame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.voltTrip_OUT.setFont(font)
        self.voltTrip_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.voltTrip_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.voltTrip_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.voltTrip_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.voltTrip_OUT.setObjectName(_fromUtf8("voltTrip_OUT"))
        self.verticalLayout_5.addWidget(self.voltTrip_OUT)
        self.horizontalLayout.addWidget(self.verticalFrame_4)
        self.verticalFrame_3 = QtGui.QFrame(self.horizontalLayout_5)
        self.verticalFrame_3.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalFrame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame_3.setObjectName(_fromUtf8("verticalFrame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_4.setMargin(3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pwrLimit_OUT = QtGui.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pwrLimit_OUT.setFont(font)
        self.pwrLimit_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.pwrLimit_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.pwrLimit_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.pwrLimit_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.pwrLimit_OUT.setObjectName(_fromUtf8("pwrLimit_OUT"))
        self.verticalLayout_4.addWidget(self.pwrLimit_OUT)
        self.pwrTrip_OUT = QtGui.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pwrTrip_OUT.setFont(font)
        self.pwrTrip_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.pwrTrip_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.pwrTrip_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.pwrTrip_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.pwrTrip_OUT.setObjectName(_fromUtf8("pwrTrip_OUT"))
        self.verticalLayout_4.addWidget(self.pwrTrip_OUT)
        self.currLimit_OUT = QtGui.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currLimit_OUT.setFont(font)
        self.currLimit_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.currLimit_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.currLimit_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.currLimit_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.currLimit_OUT.setObjectName(_fromUtf8("currLimit_OUT"))
        self.verticalLayout_4.addWidget(self.currLimit_OUT)
        self.currTrip_OUT = QtGui.QLabel(self.verticalFrame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currTrip_OUT.setFont(font)
        self.currTrip_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.currTrip_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.currTrip_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.currTrip_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.currTrip_OUT.setObjectName(_fromUtf8("currTrip_OUT"))
        self.verticalLayout_4.addWidget(self.currTrip_OUT)
        self.horizontalLayout.addWidget(self.verticalFrame_3)
        self.verticalFrame_2 = QtGui.QFrame(self.horizontalLayout_5)
        self.verticalFrame_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalFrame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame_2.setObjectName(_fromUtf8("verticalFrame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setMargin(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.capVolt_OUT = QtGui.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.capVolt_OUT.setFont(font)
        self.capVolt_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.capVolt_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.capVolt_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.capVolt_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.capVolt_OUT.setObjectName(_fromUtf8("capVolt_OUT"))
        self.verticalLayout_3.addWidget(self.capVolt_OUT)
        self.capTrip_OUT = QtGui.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.capTrip_OUT.setFont(font)
        self.capTrip_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.capTrip_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.capTrip_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.capTrip_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.capTrip_OUT.setObjectName(_fromUtf8("capTrip_OUT"))
        self.verticalLayout_3.addWidget(self.capTrip_OUT)
        self.phaseLimit_OUT = QtGui.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.phaseLimit_OUT.setFont(font)
        self.phaseLimit_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.phaseLimit_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.phaseLimit_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.phaseLimit_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseLimit_OUT.setObjectName(_fromUtf8("phaseLimit_OUT"))
        self.verticalLayout_3.addWidget(self.phaseLimit_OUT)
        self.phaseTrip_OUT = QtGui.QLabel(self.verticalFrame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.phaseTrip_OUT.setFont(font)
        self.phaseTrip_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.phaseTrip_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.phaseTrip_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.phaseTrip_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseTrip_OUT.setObjectName(_fromUtf8("phaseTrip_OUT"))
        self.verticalLayout_3.addWidget(self.phaseTrip_OUT)
        self.horizontalLayout.addWidget(self.verticalFrame_2)
        self.verticalLayout.addWidget(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QWidget(self.verticalLayout_7)
        self.horizontalLayout_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setMargin(3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalFrame_5 = QtGui.QFrame(self.horizontalLayout_4)
        self.verticalFrame_5.setMaximumSize(QtCore.QSize(800, 480))
        self.verticalFrame_5.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalFrame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame_5.setObjectName(_fromUtf8("verticalFrame_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_6.setMargin(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.dcFault_OUT = QtGui.QLabel(self.verticalFrame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dcFault_OUT.setFont(font)
        self.dcFault_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.dcFault_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.dcFault_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.dcFault_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.dcFault_OUT.setObjectName(_fromUtf8("dcFault_OUT"))
        self.verticalLayout_6.addWidget(self.dcFault_OUT)
        self.aux1_OUT = QtGui.QLabel(self.verticalFrame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aux1_OUT.setFont(font)
        self.aux1_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.aux1_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.aux1_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.aux1_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.aux1_OUT.setObjectName(_fromUtf8("aux1_OUT"))
        self.verticalLayout_6.addWidget(self.aux1_OUT)
        self.aux2_OUT = QtGui.QLabel(self.verticalFrame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aux2_OUT.setFont(font)
        self.aux2_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.aux2_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.aux2_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.aux2_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.aux2_OUT.setObjectName(_fromUtf8("aux2_OUT"))
        self.verticalLayout_6.addWidget(self.aux2_OUT)
        self.airPress_OUT = QtGui.QLabel(self.verticalFrame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.airPress_OUT.setFont(font)
        self.airPress_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.airPress_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.airPress_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.airPress_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.airPress_OUT.setObjectName(_fromUtf8("airPress_OUT"))
        self.verticalLayout_6.addWidget(self.airPress_OUT)
        self.dmPump_OUT = QtGui.QLabel(self.verticalFrame_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dmPump_OUT.setFont(font)
        self.dmPump_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.dmPump_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.dmPump_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.dmPump_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.dmPump_OUT.setObjectName(_fromUtf8("dmPump_OUT"))
        self.verticalLayout_6.addWidget(self.dmPump_OUT)
        self.horizontalLayout_2.addWidget(self.verticalFrame_5)
        self.verticalFrame_7 = QtGui.QFrame(self.horizontalLayout_4)
        self.verticalFrame_7.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalFrame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame_7.setObjectName(_fromUtf8("verticalFrame_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_9.setMargin(3)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.heatsinkWater_OUT = QtGui.QLabel(self.verticalFrame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.heatsinkWater_OUT.setFont(font)
        self.heatsinkWater_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.heatsinkWater_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.heatsinkWater_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.heatsinkWater_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.heatsinkWater_OUT.setObjectName(_fromUtf8("heatsinkWater_OUT"))
        self.verticalLayout_9.addWidget(self.heatsinkWater_OUT)
        self.inletWater_OUT = QtGui.QLabel(self.verticalFrame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inletWater_OUT.setFont(font)
        self.inletWater_OUT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 144, 0);"))
        self.inletWater_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.inletWater_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.inletWater_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.inletWater_OUT.setObjectName(_fromUtf8("inletWater_OUT"))
        self.verticalLayout_9.addWidget(self.inletWater_OUT)
        self.psuWater_OUT = QtGui.QLabel(self.verticalFrame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.psuWater_OUT.setFont(font)
        self.psuWater_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.psuWater_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.psuWater_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.psuWater_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.psuWater_OUT.setObjectName(_fromUtf8("psuWater_OUT"))
        self.verticalLayout_9.addWidget(self.psuWater_OUT)
        self.doorSwitch_OUT = QtGui.QLabel(self.verticalFrame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doorSwitch_OUT.setFont(font)
        self.doorSwitch_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.doorSwitch_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.doorSwitch_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.doorSwitch_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.doorSwitch_OUT.setObjectName(_fromUtf8("doorSwitch_OUT"))
        self.verticalLayout_9.addWidget(self.doorSwitch_OUT)
        self.coolingTower_OUT = QtGui.QLabel(self.verticalFrame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.coolingTower_OUT.setFont(font)
        self.coolingTower_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.coolingTower_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.coolingTower_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.coolingTower_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.coolingTower_OUT.setObjectName(_fromUtf8("coolingTower_OUT"))
        self.verticalLayout_9.addWidget(self.coolingTower_OUT)
        self.horizontalLayout_2.addWidget(self.verticalFrame_7)
        self.verticalFrame_6 = QtGui.QFrame(self.horizontalLayout_4)
        self.verticalFrame_6.setStyleSheet(_fromUtf8("background-color: rgb(0, 139, 255);"))
        self.verticalFrame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.verticalFrame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalFrame_6.setObjectName(_fromUtf8("verticalFrame_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_8.setMargin(3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.dmPump_OUT_2 = QtGui.QLabel(self.verticalFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dmPump_OUT_2.setFont(font)
        self.dmPump_OUT_2.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.dmPump_OUT_2.setFrameShape(QtGui.QFrame.Panel)
        self.dmPump_OUT_2.setFrameShadow(QtGui.QFrame.Raised)
        self.dmPump_OUT_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dmPump_OUT_2.setObjectName(_fromUtf8("dmPump_OUT_2"))
        self.verticalLayout_8.addWidget(self.dmPump_OUT_2)
        self.emergency_OUT = QtGui.QLabel(self.verticalFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emergency_OUT.setFont(font)
        self.emergency_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.emergency_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.emergency_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.emergency_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.emergency_OUT.setObjectName(_fromUtf8("emergency_OUT"))
        self.verticalLayout_8.addWidget(self.emergency_OUT)
        self.outletWater_OUT = QtGui.QLabel(self.verticalFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.outletWater_OUT.setFont(font)
        self.outletWater_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.outletWater_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.outletWater_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.outletWater_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.outletWater_OUT.setObjectName(_fromUtf8("outletWater_OUT"))
        self.verticalLayout_8.addWidget(self.outletWater_OUT)
        self.coilWater_OUT = QtGui.QLabel(self.verticalFrame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.coilWater_OUT.setFont(font)
        self.coilWater_OUT.setStyleSheet(_fromUtf8("color: rgb(0, 144, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.coilWater_OUT.setFrameShape(QtGui.QFrame.Panel)
        self.coilWater_OUT.setFrameShadow(QtGui.QFrame.Raised)
        self.coilWater_OUT.setAlignment(QtCore.Qt.AlignCenter)
        self.coilWater_OUT.setObjectName(_fromUtf8("coilWater_OUT"))
        self.verticalLayout_8.addWidget(self.coilWater_OUT)
        self.horizontalFrame_3 = QtGui.QFrame(self.verticalFrame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setStyleSheet(_fromUtf8(""))
        self.horizontalFrame_3.setFrameShape(QtGui.QFrame.Panel)
        self.horizontalFrame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.horizontalFrame_3.setObjectName(_fromUtf8("horizontalFrame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_rst = QtGui.QPushButton(self.horizontalFrame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rst.sizePolicy().hasHeightForWidth())
        self.btn_rst.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rst.setFont(font)
        self.btn_rst.setMouseTracking(True)
        self.btn_rst.setStyleSheet(_fromUtf8("background-color: rgb(0, 163, 244);"))
        self.btn_rst.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Picture9.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rst.setIcon(icon)
        self.btn_rst.setIconSize(QtCore.QSize(16, 16))
        self.btn_rst.setAutoDefault(True)
        self.btn_rst.setDefault(False)
        self.btn_rst.setFlat(False)
        self.btn_rst.setObjectName(_fromUtf8("btn_rst"))
        self.horizontalLayout_3.addWidget(self.btn_rst)
        self.btn_bck = QtGui.QPushButton(self.horizontalFrame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bck.sizePolicy().hasHeightForWidth())
        self.btn_bck.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bck.setFont(font)
        self.btn_bck.setMouseTracking(True)
        self.btn_bck.setStyleSheet(_fromUtf8("background-color: rgb(0, 163, 244);"))
        self.btn_bck.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Picture10.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_bck.setIcon(icon1)
        self.btn_bck.setIconSize(QtCore.QSize(14, 15))
        self.btn_bck.setAutoDefault(True)
        self.btn_bck.setDefault(False)
        self.btn_bck.setFlat(False)
        self.btn_bck.setObjectName(_fromUtf8("btn_bck"))
        self.horizontalLayout_3.addWidget(self.btn_bck)
        self.verticalLayout_8.addWidget(self.horizontalFrame_3)
        self.horizontalLayout_2.addWidget(self.verticalFrame_6)
        self.verticalLayout.addWidget(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.verticalLayout_7)

        self.retranslateUi(InterlockParams)
        QtCore.QMetaObject.connectSlotsByName(InterlockParams)

    def retranslateUi(self, InterlockParams):
        InterlockParams.setWindowTitle(QtGui.QApplication.translate("InterlockParams", "Interlock Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.freqLimit_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.freqTrip_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.voltLimit_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.voltTrip_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pwrLimit_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pwrTrip_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.currLimit_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.currTrip_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.capVolt_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.capTrip_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseLimit_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseTrip_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dcFault_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.aux1_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.aux2_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.airPress_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dmPump_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.heatsinkWater_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.inletWater_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.psuWater_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.doorSwitch_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.coolingTower_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dmPump_OUT_2.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.emergency_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.outletWater_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.coilWater_OUT.setText(QtGui.QApplication.translate("InterlockParams", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
